version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    env_file:
      - ./apps/backend/.env
