version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    env_file:
      - ./apps/backend/.env
  web:
    build:
      context: ./
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./apps/web/.env.local