name: Main
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install

      - name: Build packages
        run: npx lerna run build --ignore="{web,backend}"

      - name: Eslint
        run: npm run lint

      - name: Type Check
        run: npm run type-check
